version: "2"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: edctf
      POSTGRES_PASSWORD: edctf
    container_name: edctf_db
    restart: unless-stopped
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    container_name: edctf_web
    restart: unless-stopped
    depends_on:
      - db
