version: "2"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: edctf
      POSTGRES_PASSWORD: edctf
    container_name: edctf_db
  web:
    build: 
        context: .
        dockerfile: docker/prod/Dockerfile
    ports:
     - "80:80"
     - "443:443"
    container_name: edctf_web
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - db
