version: "2"
services:
  db:
    image: postgres
  web:
    build: 
        context: .
        dockerfile: docker/prod/Dockerfile
    ports:
     - "80:80"
     - "443:443"
    container_name: edctf_server
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - db
